### ISSUE TITLE
Roadmap to v3

### ISSUE THREAD

**Issue by nake89** [tiged/tiged#120]
# Roadmap to v3

- [ ] Remove `rimraf` dependency. `fs.rmSync(dir, { recursive: true, force: true });` has been supported since node v14. rimraf has disgusting dependency graph. See pic below.
- [ ] Replace fuzzysearch with either proper damerau-levenshtein dep (the most user friendly fuzzy search algorithm) or just include current fuzzysearch as a file. It is a dependency that is unlikely to get updated. Unlikely (impossible) to have any security issues. It is one function, MIT licensed. Just include the function in the `utils.ts` with license.
- [ ] Replace tar with nanotar. Issues is, that it is very new. But if I can get it to reliably work. I am infavor of doing this, because of the dependency graph, which again I don't like.
- [ x ] Remove `fs-extra`. @aryaemami59 already did this. Thanks!
- [ ] Replace `colorette` with `ansis`. https://dev.to/webdiscus/comparison-of-nodejs-libraries-to-colorize-text-in-terminal-4j3a
- [ ] Possibly replace `mri` and use our own version. I have this halfway done. But getting it to work with a 100s of the different ways of writing cli arguments and not breaking anybody's CI/CD is what is worrying me. That said, I would like to remove this dep, because it should otherwise be quite trivial to recreate.
- [ ] Use semantic-release to automatically update versions, changelog and to publish.
- [ x ] Bunch of fixes and changes that we've already done regarding v3 which I'm unwilling to type again as they are in the changelog: https://github.com/tiged/tiged/blob/main/CHANGELOG.md

I want our dependencies to be few and small. I want our versioning to be automated. I want quick version publishing as long the tests pass.
 
Current dependency graph:
![image](https://github.com/user-attachments/assets/3296dfab-0b07-4c95-a99c-0190fcfa76e6)

**Comment by leeoniya** [comment]
> * Replace fuzzysearch with either proper damerau-levenshtein dep (the most user friendly fuzzy search algorithm) or just include current fuzzysearch as a file. It is a dependency that is unlikely to get updated. Unlikely (impossible) to have any security issues. It is one function, MIT licensed. Just include the function in the `utils.ts` with license.

take a look at https://github.com/leeoniya/uFuzzy

side-by-side against `fuzzysearch`:

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,fuzzysearch&search=super%20ma
